### PR TITLE
Adds first UI tests for SessionDetailActivity using Espresso.

### PR DESCRIPTION
**Pull request by thagikura**
The tests verify initial views are correctly rendered and external Intents are
correctly thrown when clicking the Twitter/GitHub icons by launching the SessionDetailActivity
on connected emulators or devices.

Note that this is the first time for me to setup an emulator on CircleCI.
I referred to [this document](https://circleci.com/docs/android) on how to run an emulator on the CircleCI.
If the pre-submit fails, let me play around the setup until the pre-submit becomes green.

### CODE REVIEW

**Comment by konifar** [comment]
:eyes:

**Comment by konifar** [comment]
Have you ever set up Circle CI + Espresso? Could you help to set up circle.yml if you can? :sob: :bow: 
@hotchemi @KeithYokoma @hkurokawa

**Comment by hkurokawa** [comment]
@konifar OK. I will take a look.

**Comment by thagikura** [comment]
FYI 

I've found CircleCI people created a sample project using Espresso.
https://github.com/circleci/EspressoSample
Trying that way..

**Comment by konifar** [comment]
Yeah! Thanks!

**Comment by hkurokawa** [comment]
LGTM! :shipit:

**Comment by thagikura** [comment]
Thanks! Let me add another minor commit to explain those settings introduced by this PR was inspired by the sample project.

Or if you prefer, I can squash the commits in one commit. Which do you prefer?

**Comment by konifar** [comment]
Thanks! I prefer commented one. It is great helpful for me.

**Comment by konifar** [comment]
LGTM!

**Pull request merged**
