### PR TITLE
Fix issue of don't keep activities

### PR DESCRIPTION
**Pull request by sys1yagi**
## Related issue

#95 

## Problem

>When I opened a detail screen of a talk and go back to the "All Sessions" screen with the back button, the app crashed and logged below stack trace.

## Cause

Crash point is [SessionsFragment.java#L175](https://github.com/konifar/droidkaigi2016/blob/master/app/src/main/java/io/github/droidkaigi/confsched/fragment/SessionsFragment.java#L175).

`SessionsFragment#onActivityResult()` is unnecessary. FragmentActivity calls onActivityResult() of the child Fragment automatically. So, you should using the Fragment#startActivityForResult(). 

## Solution

- 044e13c Initialize a fragment only when savedInstanceState of the Activity is null.
- 965a857 Use Fragment#startActivityForResult(). I added the method for Fragment#startActivityForResult() to ActivityNavigator.
- e8b3245 Remove unnecessary codes.

## Tests

Verified the following:

- [x] With "Don't keep activities" on, I opened a session detail and added it to my schedule and return back to the All Sessions to see the session was checked
- [x] With "Don't keep activities" off, I opened a session detail and added it to my schedule and return back to the All Sessions to see the session was checked

### CODE REVIEW

**Comment by sys1yagi** [comment]
@hkurokawa Could you review this when you have time?

**Comment by konifar** [comment]
:eyes:

**Comment by hkurokawa** [comment]
@sys1yagi Thank you for your fix.  It is great.

By the way, I feel like `SearchActivity` need to do a similar behaviour at `onActivityResult()` as it is currently does not use `REQ_DETAIL` any other place than where it calls `activityNavigator.showSessionDetail()` when an item is pressed.  And I verified the below steps caused a problem. How do you think?

1. Click the magnifying glass to open search screen
2. Input any text to show the search result
3. Open a session
4. Click the star icon to add the session to my schedule
5. Press Back button to return to the search result
6. Open the same session again
7. The star is not turned on

**Comment by sys1yagi** [comment]
ic, I'll fix it as well. :wink:

**Comment by sys1yagi** [comment]
SearchActivity issue is complicated and it has nothing to do with this PR.
I'll correct it separately. Do you mind?

**Comment by hkurokawa** [comment]
@sys1yagi Oh, sorry for that.  No, don't mind.  Please create another PR and let me know when this PR is ready to merge.  I will merge that.

**Comment by konifar** [comment]
@sys1yagi Great thanks!!

**Comment by konifar** [comment]
LGTM!
Thanks for your fix! I will merge now because this PR might be conflicted.

**Comment by sys1yagi** [comment]
thank! I'm writing detail of this change now.

**Comment by sys1yagi** [comment]
Detail of this changes. (Japanese) https://gist.github.com/sys1yagi/b0596187917501331707

**Comment by konifar** [comment]
@sys1yagi Thanks! I'll read it :bow:

**Pull request merged**
