### PR TITLE
Update Dagger 2.2 -> 2.6

### PR DESCRIPTION
**Pull request by shaunkawano**
https://github.com/google/dagger/releases

🐹

### CODE REVIEW

**Comment by hotchemi** [comment]
Dup of https://github.com/konifar/droidkaigi2016/pull/370? Umm 💭

**Comment by hkurokawa** [comment]
Related to this one? http://stackoverflow.com/questions/33404552/execution-failed-for-task-appcompiledebugjavawithjavac-in-android-studio

**Comment by konifar** [comment]
How kind you guys are...

**Comment by shaunkawano** [comment]
Sorry guys... yes, it is duplicated (totally forgot about another pr was there) and I think I have not checked properly ... (seemed to me this dagger 2.6 is working just fine when I tested locally)

**Comment by shaunkawano** [comment]
@hkurokawa Yes you are right; it replicates locally by running `compileDevelopDebugJavaWithJavac`.

```java
注意:Generating a MembersInjector for io.github.droidkaigi.confsched.activity.MainActivity. Prefer to run the dagger processor over that class instead.
注意:Generating a MembersInjector for io.github.droidkaigi.confsched.activity.SearchActivity. Prefer to run the dagger processor over that class instead.
注意:[OrmaProcessor] process classes in 133ms
/xxx/xxx/Documents/xxx/droidkaigi2016/app/src/main/java/io/github/droidkaigi/confsched/MainApplication.java:13: エラー: シンボルを見つけられません
import io.github.droidkaigi.confsched.di.DaggerAppComponent;
                                        ^
  シンボル:   クラス DaggerAppComponent
  場所: パッケージ io.github.droidkaigi.confsched.di
:app:compileDevelopDebugJavaWithJavac FAILED
:app:compileRetrolambdaDevelopDebug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDevelopDebugJavaWithJavac'.
> java.lang.NoSuchMethodError: com.google.common.collect.FluentIterable.append(Ljava/lang/Iterable;)Lcom/google/common/collect/FluentIterable;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 13.11 secs
com.google.common.collect.FluentIterable.append(Ljava/lang/Iterable;)Lcom/google/common/collect/FluentIterable;
```

**Comment by hkurokawa** [comment]
@shaunkawano As Gradle Plugin for Android is updated with PR #396, I believe now you can upgrade Dagger without an error. Why don't you give a try? 😉

**Comment by konifar** [comment]
@hkurokawa Cool 😎

**Comment by shaunkawano** [comment]
@hkurokawa Amazing! Yes I will try it now 👍

**Comment by konifar** [comment]
I hope 🙏

**Comment by shaunkawano** [comment]
hmmm before even I start updating Dagger library, I'm kind of stuck with this error:

```
Error:Cause: com/android/build/gradle/internal/model/DefaultAndroidProject : Unsupported major.minor version 52.0
```

After a few-minute-search, I have found that this error is related to my local JDK location, which is this:

```/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home
```

But I'm still trying to figure out what's causing this error.. Does anybody have the same issue?

**Comment by shaunkawano** [comment]
I will try this: http://stackoverflow.com/a/37467179/5449688

**Comment by shaunkawano** [comment]
hmmm it did not solve my problem..! Seems like I need to reset local JDK location or create one for Android Studio? 

http://stackoverflow.com/questions/37466744/android-studio-continues-to-get-a-unsupported-major-minor-version-52-0

**Comment by konifar** [comment]
Hmm... Thanks! I also try this later

**Comment by hkurokawa** [comment]
@shaunkawano Sorry, probably I should have explained more details. The thing is, I guess, you didn't merge the latest master branch. If you upgraded Gradle Plugin for Android, I am sure you can solve this build error. Could you try to merge the latest build and see how the build goes?

**Comment by shaunkawano** [comment]
@hkurokawa Thank you for your details; actually this error has occurred right after I merged the latest master branch into my local one, (even before I re-update Dagger to 2.6), so I am guessing the cause of this error is something different...

**Comment by hkurokawa** [comment]
My apology for my misunderstanding 🙇 
I created another PR to update Dagger 2. It seems the compile went well. I have no idea why this PR doesn't get compiled.
https://github.com/konifar/droidkaigi2016/pull/395

Do you mind if I ask @konifar to merge that PR instead of this? Appreciate your hard work.

**Comment by konifar** [comment]
Agree. Thanks your work @shaunkawano !

**Comment by shaunkawano** [comment]
@hkurokawa Again, thank you very much for your info! 

> I have no idea why this PR doesn't get compiled.

Neither do I; I will keep investigating what is causing my local build to fail but anyhow great we eventually made it!!

**Comment by shaunkawano** [comment]
Dup of #395

**Pull request closed without merging**
