### PR TITLE
Change search icon in map page

### PR DESCRIPTION
**Pull request by yaeda**
Implemented #244 

like this...
screen_50

How do you think? @konifar

### CODE REVIEW

**Comment by konifar** [comment]
Awesome...!

**Comment by konifar** [comment]
I guess `ic_list` is better. What do you think?

material_icons_-_google_design

**Comment by konifar** [comment]
Almost perfect!

**Comment by yaeda** [comment]
I choosen `view list` becasue I felt term of `view` fit to this case. However, to be honest, I think both are fine. :smile:

**Comment by yaeda** [comment]
Do you want to change to `list`?

**Comment by konifar** [comment]
Could you show me screenshot applied `list` icon if you can? :bow: 
And then I want to decide which is better.

**Comment by yaeda** [comment]
screen_list
screen_view_list

`list` and `view list`

**Comment by konifar** [comment]
Thanks! Hmm...I guess view_list you chosen is better :+1:

**Comment by konifar** [comment]
LGTM! Thanks for your great fix :)

**Comment by yaeda** [comment]
OK. Thank you for your reviewing!

**Pull request merged**
