### PR TITLE
Update kvs-schema version to 3.0.0

### PR DESCRIPTION
**Pull request by rejasupotaro**
# Overview

I updated kvs-schema version. This diff is

* Generate initialize method in compile time
* Enable to specify builder class

This change makes schema class simple :smile: 

```java
@Table(name = "io.github.droidkaigi.confsched_preferences")
public abstract class DefaultPrefsSchema {
    @Key("current_language_id")
    String languageId;
    @Key("notification_setting")
    boolean notificationFlag;
    @Key("heads_up_setting")
    boolean headsUpFlag;
    @Key("show_local_time")
    boolean showLocalTimeFlag;
}
```

# Detail

Previously, we need to write singleton code manually. To reduce boilerplate code, I updated the library to generate initialize method.

```
@Table(name = "io.github.droidkaigi.confsched_preferences")
 public abstract class DefaultPrefsSchema {
     ...
-
-    private static DefaultPrefs prefs;
-
-    public static synchronized DefaultPrefs get(Context context) {
-        if (prefs == null) {
-            prefs = new DefaultPrefs(context);
-        }
-        return prefs;
-    }
 }
```

Actual generated code is below.

```java
public final class DefaultPrefs extends PrefsSchema {

  private static DefaultPrefs singleton;

  public static DefaultPrefs get(Context context) {
    if (singleton != null) return singleton;
    synchronized (DefaultPrefs.class) { if (singleton == null) singleton = new DefaultPrefs(context); };
    return singleton;
  }
```

We can get a singleton instance of DefaultPrefs by `DefaultPrefs.get` directly.

In addition, from 3.0.0, we can specify builder class by `@Table(builder = *.class)` for DefaultPrefs to change creation mode or use custom SharedPreferences. But it is for special case. We don't have to specify builder class at least in this project.

# Related links

- [Create initialize methods in a compile time · Issue #10 · rejasupotaro/kvs-schema](https://github.com/rejasupotaro/kvs-schema/issues/10)
- [Generate initialize methods in compile time by rejasupotaro · Pull Request #11 · rejasupotaro/kvs-schema](https://github.com/rejasupotaro/kvs-schema/pull/11)
- [Enable to specify builder class by rejasupotaro · Pull Request #12 · rejasupotaro/kvs-schema](https://github.com/rejasupotaro/kvs-schema/pull/12)

### CODE REVIEW

**Comment by konifar** [comment]
:eyes:

**Comment by sys1yagi** [comment]
:cool: :star2:

**Comment by konifar** [comment]
Great improvement! I love it :heart_eyes:

**Comment by konifar** [comment]
LGTM!

**Comment by gfx** [comment]
It's just a question: why not to use DI?

**Comment by rejasupotaro** [comment]
Thank you for your question.

It is possible. Actually, I attempted to inject prefs at first.

But we are using prefs in *Util class in this project. We shouldn't inject these classes. Hence, we have to use 2 ways properly when we inject it.

```java
// In injectable classes
@Inject
DefaultPrefs defaultPrefs;
...
defaultPrefs.getLanguageId();

// In not injectable classes
DefaultPrefs.get(context).getLanguageId();
``` 

kvs-schema manages a singleton instance of DefaultPrefs. At the same time, Dagger manages a singleton instance of DefaultPrefs as well. There is no effect on retrieving data but it seems a little bit complicated. To avoid confusion, I decided to use `DefaultPrefs.get` in this project for now.

**Pull request merged**
