### PR TITLE
Update gradle version to 2.11

### PR DESCRIPTION
**Pull request by cafedeaqua**
# Purpose
* Improve build performance

# Result
* measurement with 3 times
```
$ git checkout feature_update_gradle_version
$ ./gradlew clean
$ time ./gradlew assembleDebug

Total time: 2 mins 56.459 secs
Total time: 2 mins 55.672 secs
Total time: 2 mins 51.675 secs
```

```
$ git checkout master
$ ./gradlew clean
$ time ./gradlew assembleDebug

Total time: 2 mins 55.14 secs
Total time: 2 mins 57.621 secs
Total time: 2 mins 57.106 secs
```

### CODE REVIEW

**Comment by cafedeaqua** [comment]
Please review it.

**Comment by konifar** [comment]
Maybe it looks good.But I cannot be sure...
Can anybody review it? :bow:

**Comment by gfx** [comment]
Looks good!

**Comment by konifar** [comment]
@gfx Thanks!

**Pull request merged**
