### PR TITLE
Set dialog theme to avoid yellow texts

### PR DESCRIPTION
**Pull request by KeithYokoma**

### CODE REVIEW

**Comment by hotchemi** [comment]
Could u provide a gif or img which shows how it changed?

**Comment by KeithYokoma** [comment]
Previously confirmation texts are yellow and the dialog title is white.
before

Now it is safe to see them 🙋
after

**Comment by hotchemi** [comment]
Awesome!

**Comment by konifar** [comment]
Awesome!

**Comment by konifar** [comment]
LGTM

**Comment by KeithYokoma** [comment]
Merge!

**Pull request merged**
