### PR TITLE
Fix in-app locale being reset on orientation change

### PR DESCRIPTION
**Pull request by ypresto**
Orientation change causes broken layout and string.

screenshot_20160218-151710

Special thanks to @ichigotake ..!!!

### CODE REVIEW

**Comment by konifar** [comment]
:eyes:

**Comment by KeithYokoma** [comment]
[LGTM](http://lgtm.in/i/kagNDcniq)

[:+1:](http://lgtm.in/u/kagNDcniq)

**Comment by konifar** [comment]
Thanks! By the way, Great work for your session :+1: 
I couldn't hear, but I read your slide. Interesting.

**Comment by konifar** [comment]
LGTM

**Comment by ypresto** [comment]
Thanks!! Well, but, I don't have any sessions on this conf as it was rejected.. :)

**Comment by konifar** [comment]
Oh, really? Sorry.... My mistake...

**Comment by ypresto** [comment]
Don't mind! I'll talk it in another chance! ;)

**Comment by ichigotake** [comment]
@ypresto Thanks to call me for pair programing! :dancers:

**Pull request merged**
