### PR TITLE
Update README.md for a tiny bit

### PR DESCRIPTION
**Pull request by shaunkawano**
This pull request corresponds to #105 

Everything on README has already looked great but I tied to improve it even for a tiny bit.

I've tried to avoid any change that may cause unintended contextual modification but if anything seems weird, wrong, or irrelevant, feel free to add some comment or make revision right away! :dancer:

### CODE REVIEW

**Comment by konifar** [comment]
Great fix! It's very helpful for me :+1: 

LGTM!

**Comment by konifar** [comment]
Could you merge this after CI finished?

**Comment by shaunkawano** [comment]
OK! Glad to hear that! :)

**Comment by shaunkawano** [comment]
Could I possibly have write access to this repository or konifar-san can merge it if that's better! :dancer:

**Comment by konifar** [comment]
Oh sorry. I'll merge this now.

**Comment by shaunkawano** [comment]
Thank you! :+1:

**Pull request merged**
