### PR TITLE
Simplify VideoPlayerActivity

### PR DESCRIPTION
**Pull request by ogapants**
I removed the feature that does not seem to use in VideoPlayerActivity.
If you will use it in future, please close this PR.

### CODE REVIEW

**Comment by konifar** [comment]
👀

**Comment by konifar** [comment]
Looks good!
Could you put screenshot?

**Comment by hotchemi** [comment]
Thx, let me check!

**Comment by hotchemi** [comment]
Okay! I was thinking loading from local but agree with delete redundnt code for the time being!

**Comment by konifar** [comment]
Awesome PR 💪  Thanks!!

**Comment by hotchemi** [comment]
@ogapants feel free to tackle! 
https://github.com/konifar/droidkaigi2016/issues/380

**Comment by ogapants** [comment]
I'll try it if possible... 💪

**Pull request merged**
