### PR TITLE
Update RxJava to 1.1.10.

### PR DESCRIPTION
**Pull request by hotchemi**
ref: https://github.com/ReactiveX/RxJava/releases/tag/v1.1.10

### CODE REVIEW

**Comment by konifar** [comment]
👀 
I'm waiting CI...

**Comment by konifar** [comment]
LGTM! Thanks!!!

th_ _ _ 07 7 5 1

**Comment by shaunkawano** [comment]
"ただただ最高..." PR...

**Comment by hotchemi** [comment]
yabai!

**Pull request merged**
