### PR TITLE
[WIP] Kotlin

### PR DESCRIPTION
**Pull request by konifar**
https://github.com/konifar/droidkaigi2016/issues/329

### CODE REVIEW

**Comment by konifar** [comment]
Just created `kotlin` branch.

**Comment by hotchemi** [comment]
Has anyone been working on it? Actually...it seems....we've lost the motivation... 🌵

**Comment by konifar** [comment]
Exactly 😅

**Comment by hotchemi** [comment]
Okay, next year we might be going to try!

**Comment by konifar** [comment]
Yep. Thanks for your patrol! 👍

**Comment by hotchemi** [comment]
👮

**Pull request closed without merging**
