### PR TITLE
Remove debug build deploy

### PR DESCRIPTION
**Pull request by konifar**
Removed debug build deploy to Deploygate, because `1.0.0` was already released.

### CODE REVIEW

**Comment by konifar** [comment]
I already changed Deploygate link in README.
https://github.com/konifar/droidkaigi2016/commit/17141133555ed59ecbcf3f11489096b64bdcbd45

**Comment by hkurokawa** [comment]
Great.  Just two things to confirm.

1. Maybe we can just remove the snippets not uncommenting them as we no longer need them in future.
2. I am wondering whether we could skip ./gradlew clean assembleProductionRelease as it is already done with `test` phase.  Let me know your comments.

**Comment by konifar** [comment]
> Maybe we can just remove the snippets not uncommenting them as we no longer need them in future.

I see. You are right. I'll remove it.

**Comment by konifar** [comment]
I already announced old α version deploygate page.

banners_and_alerts_and_droidkaigi_2016_debug_-_deploygate

**Comment by konifar** [comment]
> I am wondering whether we could skip ./gradlew clean assembleProductionRelease

OK! It is better to remove that. Faster CI is better :)

**Comment by hkurokawa** [comment]
@konifar Thanks, let's see how it is going.

**Pull request merged**
