### PR TITLE
Fix Failure saving state: active SupportMapFragment{} has cleared index: -1

### PR DESCRIPTION
**Pull request by hkurokawa**
## Issue
#246 

## Contents
- [x] Use `MapFragment`'s FragmentTransaction instead of `MainActivity`'s.
- [x] To avoid 'Can not perform this action after onSaveInstanceState', use `commitAllowingStateLoss()` instead of `commit()` so that we can make sure the `SupportMapFragment` is removed before `MapFragment` is resumed and try to add the same Fragment to its view.

[Review on Reviewable](https://reviewable.io/reviews/konifar/droidkaigi2016/263)

### CODE REVIEW

**Comment by hotchemi** [comment]
LGTM!

**Comment by KeithYokoma** [comment]
[LGTM](http://lgtm.in/i/kagNDcniq)

[:+1:](http://lgtm.in/u/kagNDcniq)

**Comment by konifar** [comment]
LGTM!

**Comment by hkurokawa** [comment]
Thank you, guys! I will merge it after it passes CI.

**Comment by konifar** [comment]
Saikou-kayo

**Comment by hkurokawa** [comment]
FYI: Related PullRequest #229 and StackOverflow http://stackoverflow.com/questions/14124354/android-supportmapfragment-with-googlemaps-api-2-0-giving-illegalargumentexcep

**Comment by hkurokawa** [comment]
Seems another way to fix the `Error inflating class fragment` is adding the SupportMapFragment dynamically. http://stackoverflow.com/a/29077930

**Pull request merged**
