### PR TITLE
Call CompositionSubscription#unsubscribe() in Activity#onStop() instead of Activity#onDestroy()

### PR DESCRIPTION
**Pull request by suzukaze**
Call CompositionSubscription#unsubscribe() not when Activity is destroyed(Activity#onDestroy) but Activiy is hidden (Activity#onStop()).

Refere: http://qiita.com/yuya_presto/items/c8c3d77ac958c9c8f67b

### CODE REVIEW

**Comment by konifar** [comment]
:eyes: Thanks for your fix! Looks good for me.

@hkurokawa Could you review this? Because you have Rx session :)

**Comment by hkurokawa** [comment]
@suzukaze Hi, thank you for your suggestion.

Actually, I do not understand why unsubscribing at `onStop()` is better than `onDestroy()`.  Could you explain more?

In my understanding, `onStop()` is called when a user moves to another app. And if a user moves to another app while the data is being loaded, the call is cancelled and when he/she comes back to our app, we have to execute that asynchronous task once again, which is a waste. So I am just thinking to execute the task in `onCreate()` and to cancel it in `onDestory()` would be better.  What kind of concern do you have for that?

By the way, this PR has a problem that if `onStop()` is called during the network calls and the user returns back to the screen, the request is not resumed as the request is executed only in `onCreate()`. So you have to call them in `onStart()` instead of `onCreate()` as well if you want to subscribe/unsubscribe in `onStart()`/`onStop()`.

If you have any questions or comments, feel free to let me know. Thank you.

**Comment by suzukaze** [comment]
Thanks for replying @hkurokawa.

I say my opinion  bellow.

## Observable#subscribe() and  Subscription#unsbuscribe() 
After Observable#subscribe() is called, Subscription#unsbuscribe() must be called. 
This avoids memory leaks.
Subscription#unsubscribe() is automatically called when Subscriber#onCompleted() or #onError() is called.

CompositeSubscription#add() registers Subscription. CompositeSubscription#unsuscribe calls Subscription#unsubscribe() of every registered Subscription.

CompositeSubscription#unsuscribe does nothing after Subscriber#onCompleted() or #onError() is called.

CompositeSubcription#unsubcribe works if Subscriber#onCompleted() or #onError() is not called.

Beacause Activiy is hidden, there is no place in which infomation which be getting from network so subsribe should be stopped.(call Subscription#unsubscribe())

Before Subscriber#onCompleted() is called, Activiy is hidden (Activity#onStop()) so Subscriber#onCompleted() is not called. CompositeSubscription#unsuscribe calls Subscription#unsubscribe() instead of Subscriber#onCompleted() calling it.

## Where is Observable#subscribe() called?
This is antoher problem which Observable#subscribe() is called in onCreate() or onStart() inspite of CompositeSubscription#unsuscribe is being called in onStop() or onDestroy()

If Subscriber#onCompleted() is not called, Activty may not display infomation which is get from network.

Case A. Observable#subscribe() is called in onCreate().
Activy displays infomation after Subscriper#onCompleted() is called and Activity is hidden then it resumes.
Activt displays no infomation after Subscriper#onCompleted() is not called and Activity is hidden then it resumes.

Case B. Observable#subscribe() is called in onStart().
Activy displays infomation after Subscriper#onCompleted() is called and Activity is hidden then it resumes.
Activt displays no infomation after Subscriper#onCompleted() is not called and Activity is hidden then it resumes. (Activity loads infomation from network again)

**Comment by hkurokawa** [comment]
Hi @suzukaze,

Thank you for your detailed explanation.

OK. Let's discuss one by one. The original issue is `whether we should unsubscribe on onStop() or onDestroy()`. So just forget the second topic - whether we should subscribe in `onCreate()` or `onStart()`.

If I got your points correctly, the reasons why you insist `onStop()` is better than `onDestroy()` are the below two. Is my understanding correct?

1. To avoid memory leak
2. There is nothing to display on the screen after `onStop()` is called (Thus, we should just cancel the asynchronous task at that point)

As regarding point 1, I am wondering which object you are concerning about to be possibly leaked. Views? Activities? But even if `onStop()` is called, I guess they are still on the memory until they are discarded with `onDestroy()` and we can avoid the memory leak if unsubscribing on `onDestroy()`. So I could not find the advantages on using `onStop()` for the unsubscription point in terms of memory leak.

Also, I would like to point out this is the same question as an old yet popular question, `when we should cancel an asynchronous task in Android to avoid memory leak`. Right? So the problem can be said in other words "Should we cancel an AsyncTask on onStop() or onDestroy()?". I believe there is no problem to use `onDestroy()` in general as it is common way. For example, the sample code in some text books (such as [Effective Android Threading](http://shop.oreilly.com/product/0636920029397.do)) cancels the AsyncTask at `onDestroy()`.

As regarding point 2, you are correct that if we want the Activity not to do anything when it is in background (for example, showing a Fragment or views), it is an easy way to achieve that to do unsubscription at `onStop()`. But in our case, `MainActivity` and `SessionFeedbackActivity`, I believe there is no problem if we receive an event while the activity is in background. And I am concerning about we have to introduce a new logic to manage a state if we move the unsubscription point to `onStop()`.

For example, assume you press a submit button on `SessionFeedbackActivity` and immediately moves to another app. In that case, if you cancel the subscription in `onStop()`, the result dialogs would not be shown even after the submit finishes. Right? And you come back to our app to see the screen without the result dialogs. You may think "Ah, the submit does not finish yet" and would press the button again. To avoid that, we have to introduce a flag to tell whether the submit finishes already or not and show the dialog at `onStart()` if it is already done. I am just reluctant to do that.

All in all, I cannot see the disadvantages to use `onDestroy()` as the unsubscription point in `MainActivity` and `SessionFeedbackActivity` yet (please note I am not talking about the general case). If there is any clear disadvantages, I am willing to move the unsubscription point to `onStop()` with some extra works.

Feel free to correct me if I am wrong or I misunderstood something.

Thank you.

**Comment by suzukaze** [comment]
1. I don't say CompositeSubscription#unsubscribe() in onDesroy() cause memory leaks. 
CompositeSubscription#unsubscribe() in onStop() or onDesroy()  avoids memory leacks. 
I say this topic to explain that it is necessary to call  CompositeSubscription #unsubscribe() becase of not calling onCompleted() or onError(),

This case it is no advantage to call onStop() than onDestroy().
Because subscribe in onCreate() one time is called,  CompositeSubscription has a registered subscription.

When it is not nesecassary to subscribe, it is natural that CompositeSubscription#unsubscribe() is called immidately.

CompositeSubscription#unsubscribe() in onDestroy works but CompositeSubscription#unsubscribe() in onStop works earlier (Activity is hidden or destroyed)

In this appli, compositeSubscription has a registered subscription so memory consume is not many so that it is no advantage of calling unsubscribe() earlier.

2. This is a corner case. I understand you doesn't want to implement that using flag.  Me, neither.

**Comment by hkurokawa** [comment]
Hi @suzukaze,

Thank you for your clarification and pointing out my misunderstanding of your saying about memory leak. Sorry for that.

Here, I believe we agreed on there is not so strong motivation to apply the PR as our usage of Rx is limited and a bit unusual.

Thus, I am closing the PR and if you have any other concerns, feel free to re-open this.

Deeply appreciate your suggestion on the improvement and thank you for your understanding.

**Comment by suzukaze** [comment]
Thank you @hkurokawa

**Pull request closed without merging**
