### PR TITLE
Fix IndexOutOfBoundsException when back to "All Sessions" screen

### PR DESCRIPTION
**Pull request by hkurokawa**
## Related issue
#95 

## Contents
- [x] Check the size of the fragments and return `null` if it is out of bounds

## Regression tests
Verified the following:
- [x] With "Don't keep activities" on, I opened a session detail and added it to my schedule and return back to the All Sessions to see the session was checked
- [x] With "Don't keep activities" off, I opened a session detail and added it to my schedule and return back to the All Sessions to see the session was checked

[Review on Reviewable](https://reviewable.io/reviews/konifar/droidkaigi2016/98)

### CODE REVIEW

**Comment by hkurokawa** [comment]
@konifar Could you review this when you have time?  I would like to confirm it does not break any existing behaviour.

**Comment by hotchemi** [comment]
@hkurokawa When it returns null, aren't there any problem right? I think it is related with this line.
https://github.com/konifar/droidkaigi2016/blob/f5c669f356e5995a6928631aaff7e657a3a6ad24/app/src/main/java/io/github/droidkaigi/confsched/fragment/SessionsFragment.java#L176

**Comment by hkurokawa** [comment]
@hotchemi You're correct.  My concern is if there is no Fragments at that point of `onActivityResult()`, I can just do nothing or I should do anything else.

**Comment by konifar** [comment]
LGTM!

**Comment by hkurokawa** [comment]
Thanks! I am merging this.

**Comment by sys1yagi** [comment]
Hi, I think this PR is not enough.

-  Fragment should not initialize when savedInstanceState of the Activity is null.
  - ref : [SimpleSinglePaneActivity.java#L45](https://github.com/google/iosched/blob/b3c3ae2a5b41e28c07383644d78e5c076288322f/android/src/main/java/com/google/samples/apps/iosched/ui/SimpleSinglePaneActivity.java#L45)
  - http://developer.android.com/intl/ja/reference/android/app/Fragment.html
     - >First-time init; create fragment to embed in activity.
  - It will cause an increase in the Fragment that FragmentManager holds.
- FragmentActivity calls onActivityResult() of the child Fragment automatically. So, you should using onActivityResult() of the Fragment.
  - ref : [FragmentActivity.java#L156](https://github.com/android/platform_frameworks_support/blob/309059f029f498bf0bf2c431c9f3617915271d7f/v4/java/android/support/v4/app/FragmentActivity.java#L156)

Can I send a pull request?

**Comment by hotchemi** [comment]
@sys1yagi Why not? :+1:

**Comment by mhidaka** [comment]
@sys1yagi 

> Can I send a pull request?

offcourse, Welcome your contribution

**Comment by konifar** [comment]
@sys1yagi Sure!

**Pull request merged**
