### PR TITLE
sessions_ko.json Translate

### PR DESCRIPTION
**Pull request by Pluu**
Support Korean Language

`sessions_ko.json` Translate

### CODE REVIEW

**Comment by konifar** [comment]
Thanks! I'll check this PR tonight :+1:

**Comment by Pluu** [comment]
@konifar Please check This PR.

**Comment by konifar** [comment]
Sure!

**Comment by konifar** [comment]
LGTM! (I can't know this is correct or not... But maybe good :smile: )

**Comment by konifar** [comment]
Thanks for your contribution!

**Comment by Pluu** [comment]
Thanks PR Merge.
sorry. I can't a more natural translation.

**Pull request merged**
