### PR TITLE
Remove R.string.app_close_confirm since it is no longer used.

### PR DESCRIPTION
**Pull request by shiraji**
I was working on #80 and noticed #121 didn't remove `app_close_confirm` from strings.xml

### CODE REVIEW

**Comment by konifar** [comment]
:eyes:

**Comment by konifar** [comment]
Great thanks!!

LGTM :+1:

**Comment by konifar** [comment]
I'll merge this after CI finished.

**Comment by shiraji** [comment]
Definitely out of topics but are you working on adding fragments on backstack? I found a difficulty of displaying `SessionsTabFragment` after pressing back button. I think there is something wrong with adapter.

**Comment by shiraji** [comment]
I mean I try to accomplish what you say

> 1. Show All Sessions page.
> 2. Show Map page.
> 3. Press back button.
> 4. Back to All Sessions page.

**Comment by konifar** [comment]
You mean this issue right?
https://github.com/konifar/droidkaigi2016/issues/80

KeithYokoma is already assigned and started, So could you ask him?
@KeithYokoma ping

**Comment by shiraji** [comment]
No worry if he is doing. I will stop working on the issue. Thanks.

**Comment by konifar** [comment]
OK! Anyway thanks for your fix!

**Comment by shiraji** [comment]
NP!

**Comment by mhidaka** [comment]
@shiraji thanks for your work!

**Pull request merged**
