### PR TITLE
fix lint violations

### PR DESCRIPTION
**Pull request by gfx**
**edit**: this pr only includes lint-violation fixes. Enabling `abortOnError` is a next time issue.

---

Do not disable `lintOptions.abortOnError`, which can find critical errors.

This pull-request re-enable `abortOnError` and supress critical lint errors.

FYI: https://github.com/konifar/droidkaigi2016/pull/129 enables `./gradlew check` which includes `./gradlew lint`.

@konifar: you can reject this pull-request if you don't like this. It might cause a lot of CI failures :)

### CODE REVIEW

**Comment by konifar** [comment]
Well done!

**Comment by hkurokawa** [comment]
LGTM. I agree on merging this if it does not cause any CI error (So far, it seems there is no issues on build).

**Comment by hotchemi** [comment]
Umm, we should give a priority for quick release...so we'll merge it after 1.1.0 release:D

**Comment by gfx** [comment]
Okay, disable `abortOnError` for now; now this pr includes only lint-violation fixes.

**Comment by hotchemi** [comment]
Thx! LGTM

**Comment by konifar** [comment]
LGTM! Very sorry for late reply :bow:

**Pull request merged**
