### PR TITLE
Added slide_urls

### LINKED ISSUE #293: Add slide url to json file
http://unsolublesugar.com/20160218/134940/

### PR DESCRIPTION
**Pull request by jmatsu**
Fixed #293
Added available slide_url to jsons.

### CODE REVIEW

**Comment by konifar** [comment]
:eyes:

**Comment by konifar** [comment]
Great works! Thanks!
I will add url link button in detail page!

**Comment by jmatsu** [comment]
:+1:

**Comment by konifar** [comment]
Added https://github.com/konifar/droidkaigi2016/issues/309

**Comment by konifar** [comment]
LGTM!

**Comment by jmatsu** [comment]
I used a script for adding slide_urls. Just in case, I have pushed it to Github. (https://github.com/jmatsu/updatefiles)
If you would like to use this and have any questions, please feel free to ask me.

**Pull request merged**
