### PR TITLE
Added slide url to detail page

### PR DESCRIPTION
**Pull request by konifar**
Thanks to @jmatsu. https://github.com/konifar/droidkaigi2016/pull/308

Added slide url link if it exists.

2016-02-20_07_22_05_png_and_downloads

slide section is not shown if it does not exist.

2016-02-20_07_21_57_png_and_

### CODE REVIEW

**Comment by hotchemi** [comment]
Just one suggestion, how about using HTML technique? Sometimes url link tends to be long.

```xml
<string name="link"><![CDATA[<a href-"slide link">Link</a>]]></string>
```
```java
setText(Html.fromHtml(getString(R.string.link));
```

**Comment by konifar** [comment]
Good suggestion!
But I can not decide what is the best link word. `Link` or `{Session title}` or image icon...
So I think a little bit more!

**Comment by hotchemi** [comment]
Thx! There is no deadline so please take your time.
And I found we can use this icon:) https://design.google.com/icons/#ic_public

**Comment by konifar** [comment]
Sorry, I can't find good icon... And I guess url link is better than replaced link word.
Of course I want to change if some good solution is found. 
How do you think?

**Comment by hotchemi** [comment]
OK, IMP public icon is not bad but this is your app! I definitely have respect for your opinion. Thank you.

**Comment by konifar** [comment]
Thanks! :bow:

**Pull request merged**
