### PR TITLE
Enlarge notification text

### PR DESCRIPTION
**Pull request by shaunkawano**
Corresponding issue: #245 

I've simply specified textSize to `@dimen/text_large` here.

## No TextStyle

device-2016-02-16-013950

## With Bold TextStyle

device-2016-02-16-015749

### CODE REVIEW

**Comment by konifar** [comment]
Thanks!! 
How about adding `textStyle="bold"`? I don't know which is better bold or not.

**Comment by shaunkawano** [comment]
OK! I'll apply style and add screenshot so maybe we can decide which looks better! :)

**Comment by shaunkawano** [comment]
I guess the one with Bold style applied looks better!  What do you think?

**Comment by konifar** [comment]
I agree with you :+1:

**Comment by konifar** [comment]
LGTM

**Comment by shaunkawano** [comment]
I've committed style addition as well! :) Thank you very much for reviewing my pr..!

**Pull request merged**
