### PR TITLE
fix window leak introduced in PR #154

### PR DESCRIPTION
**Pull request by zaki50**
sorry for introducing a :bug:

### CODE REVIEW

**Comment by konifar** [comment]
Oh, I didn't notice that.
Thanks for your fix!

**Comment by konifar** [comment]
LGTM!

**Comment by konifar** [comment]
I'll check why CI failded.

**Comment by zaki50** [comment]
@konifar I rebased the commits against latest master

**Comment by konifar** [comment]
I tried to do same fix from latest master branch and push, CI was suceeded... I don't know why.
Could you try to resend as another PR? I'm so sorry :bow:

**Comment by konifar** [comment]
I'm so sorry. It is our CircleCI issue. I'll fix it, so please wait :bow:

**Comment by konifar** [comment]
I fixed CircleCI setting. So could you merge or rebase latest master branch to pass CI? :bow:

**Comment by konifar** [comment]
Thanks for your fix!! Thanks!

**Pull request merged**
