### PR TITLE
Refactoring and Update dependencies

### PR DESCRIPTION
**Pull request by gotokatsuya**
### DroidKaigiClient.getSessions
- if to switch. 
  - It is easy to add languages.

### gson 2.6.1

https://github.com/google/gson/blob/master/CHANGELOG.md

### okhttp 3.1.2

https://github.com/square/okhttp/blob/master/CHANGELOG.md

### threetenabp 1.0.3

https://github.com/JakeWharton/ThreeTenABP/blob/master/CHANGELOG.md

### stetho 1.3.0

https://github.com/facebook/stetho/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by konifar** [comment]
:eyes:

**Comment by konifar** [comment]
Great thanks!! Looks good to me :ok_hand:

**Comment by gotokatsuya** [comment]
Welcome :smiley: 

Thank you for your fast work.

**Comment by konifar** [comment]
Could you check to merge or rebase latest master branch? Because CI failed. But I tried to push new branch from latest master branch, CI succeeded.

**Comment by gotokatsuya** [comment]
Sure !

**Comment by konifar** [comment]
Or could you try to resend as another PR from latest master branch? Because I don't know why CI failed... I'm so sorry :bow:

**Comment by gotokatsuya** [comment]
No problem :+1:

**Comment by konifar** [comment]
Yeah! :clap:

**Comment by konifar** [comment]
Hmm... CI is succeeded, but I guess it is better not to change CI build :bow:

**Comment by gotokatsuya** [comment]
Yes, I agree with you.

But,

This error was caused by environment-variables on circle-ci.
Maybe, I ( have no authorization ) could not get these values.

```
storePassword System.getenv("KSTOREPWD")
keyPassword System.getenv("KEYPWD")
```

**Comment by konifar** [comment]
Oh...Sorry. Let me check CircleCI!

**Comment by gotokatsuya** [comment]
Thank you so much :+1:

**Comment by konifar** [comment]
OK, I got it! It is our CircleCI Issue.
https://circleci.com/docs/fork-pr-builds

So first I merge it. I'm so sorry :bow: And thanks so much for your great fix!

**Comment by konifar** [comment]
LGTM!

**Comment by gotokatsuya** [comment]
You are welcome ! Thx for your help !! :100:

**Pull request merged**
