### PR TITLE
Remove inputType and enable line break of EditText

### PR DESCRIPTION
**Pull request by kaelaela**
Please check my PR :smiley_cat: 

### Before
device-2016-02-14-054804

### After
device-2016-02-14-055916

### CODE REVIEW

**Comment by konifar** [comment]
:eyes:

**Comment by konifar** [comment]
Thanks! But sorry... it is conflicted because I refactored `activity_session_feedback.xml` recent [PR](https://github.com/konifar/droidkaigi2016/pull/188) :bow: 

So could you merge or rebase master branch ?

**Comment by konifar** [comment]
And could you upload screenshot if possible.

**Comment by kaelaela** [comment]
Sorry... I'll fix it and add screenshot. :+1:

**Comment by kaelaela** [comment]
@konifar I've fixed it！But, if you want to do "text" inputType, this PR is bad change.

**Comment by konifar** [comment]
Thanks! But still conflicted :cry:

**Comment by konifar** [comment]
Good screenshot :clap: Thanks!

**Comment by konifar** [comment]
LGTM! Thanks!

**Pull request merged**
