### PR TITLE
Fix Orma License

### PR DESCRIPTION
**Pull request by hkurokawa**
## Issue
#84 

## Contents
- [x] Update the link for Orma with https://github.com/gfx/Android-Orma

[Review on Reviewable](https://reviewable.io/reviews/konifar/droidkaigi2016/104)

### CODE REVIEW

**Comment by hkurokawa** [comment]
@konifar Is this fix just fine for #84?

**Comment by konifar** [comment]
@hkurokawa Yes, thanks :bow:

**Comment by konifar** [comment]
LGTM!!

**Comment by hkurokawa** [comment]
Thanks :+1:

**Pull request merged**
