### PR TITLE
Back navigation to traverse the history

### PR DESCRIPTION
**Pull request by KeithYokoma**

### CODE REVIEW

**Comment by KeithYokoma** [comment]
Currently I have a issue on `MapFragment`.

When `FragmentManager#popBackStack()` for `MapFragment`, the app will crash with the following log.
```
02-15 10:50:05.931 3521-3521/io.github.droidkaigi.confsched.develop.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                            Process: io.github.droidkaigi.confsched.develop.debug, PID: 3521
                                                                                            android.view.InflateException: Binary XML file line #11: Binary XML file line #11: Error inflating class fragment
                                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                                                at android.databinding.DataBindingUtil.inflate(DataBindingUtil.java:116)
                                                                                                at io.github.droidkaigi.confsched.databinding.FragmentMapBinding.inflate(FragmentMapBinding.java:82)
                                                                                                at io.github.droidkaigi.confsched.databinding.FragmentMapBinding.inflate(FragmentMapBinding.java:79)
                                                                                                at io.github.droidkaigi.confsched.fragment.MapFragment.onCreateView(MapFragment.java:68)
                                                                                                at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
                                                                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
                                                                                                at android.support.v4.app.BackStackRecord.popFromBackStack(BackStackRecord.java:958)
                                                                                                at android.support.v4.app.FragmentManagerImpl.popBackStackState(FragmentManager.java:1666)
                                                                                                at android.support.v4.app.FragmentManagerImpl$2.run(FragmentManager.java:577)
                                                                                                at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
                                                                                                at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
                                                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                                at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                             Caused by: android.view.InflateException: Binary XML file line #11: Error inflating class fragment
                                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:782)
                                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                                                                at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                                                at android.databinding.DataBindingUtil.inflate(DataBindingUtil.java:116) 
                                                                                                at io.github.droidkaigi.confsched.databinding.FragmentMapBinding.inflate(FragmentMapBinding.java:82) 
                                                                                                at io.github.droidkaigi.confsched.databinding.FragmentMapBinding.inflate(FragmentMapBinding.java:79) 
                                                                                                at io.github.droidkaigi.confsched.fragment.MapFragment.onCreateView(MapFragment.java:68) 
                                                                                                at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962) 
                                                                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067) 
                                                                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248) 
                                                                                                at android.support.v4.app.BackStackRecord.popFromBackStack(BackStackRecord.java:958) 
                                                                                                at android.support.v4.app.FragmentManagerImpl.popBackStackState(FragmentManager.java:1666) 
                                                                                                at android.support.v4.app.FragmentManagerImpl$2.run(FragmentManager.java:577) 
                                                                                                at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613) 
                                                                                                at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517) 
                                                                                                at android.os.Handler.handleCallback(Handler.java:739) 
                                                                                                at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                                at android.os.Looper.loop(Looper.java:148) 
                                                                                                at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                                             Caused by: java.lang.IllegalArgumentException: Binary XML file line #11: Duplicate id 0x7f0e00a2, tag null, or parent id 0x7f0e007d with another fragment for com.google.android.gms.maps.SupportMapFragment
                                                                                                at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2289)
                                                                                                at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
                                                                                                at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:186)
                                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746)
                                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                                                at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                                                at android.databinding.DataBindingUtil.inflate(DataBindingUtil.java:116) 
                                                                                                at io.github.droidkaigi.confsched.databinding.FragmentMapBinding.inflate(FragmentMapBinding.java:82) 
                                                                                                at io.github.droidkaigi.confsched.databinding.FragmentMapBinding.inflate(FragmentMapBinding.java:79) 
                                                                                                at io.github.droidkaigi.confsched.fragment.MapFragment.onCreateView(MapFragment.java:68) 
                                                                                                at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962) 
                                                                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067) 
                                                                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248) 
                                                                                                at android.support.v4.app.BackStackRecord.popFromBackStack(BackStackRecord.java:958) 
                                                                                                at android.support.v4.app.FragmentManagerImpl.popBackStackState(FragmentManager.java:1666) 
                                                                                                at android.support.v4.app.FragmentManagerImpl$2.run(FragmentManager.java:577) 
                                                                                                at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613) 
                                                                                                at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517) 
                                                                                                at android.os.Handler.handleCallback(Handler.java:739) 
                                                                                                at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                                at android.os.Looper.loop(Looper.java:148) 
                                                                                                at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by KeithYokoma** [comment]
Ok now it's fixed.

ref. http://stackoverflow.com/questions/14124354/android-supportmapfragment-with-googlemaps-api-2-0-giving-illegalargumentexcep

**Comment by hotchemi** [comment]
image

**Comment by KeithYokoma** [comment]
Let’s go all-out!

**Pull request merged**
