### PR TITLE
Update retrolambda and use the latest version

### PR DESCRIPTION
**Pull request by shaunkawano**
I have updated retrolambda version so that possibly we can reduce 1500-2000 methods and have some other optimization to it.

Reference: 

https://github.com/orfjackal/retrolambda#retrolambda-230-2016-04-30

https://github.com/JakeWharton/retrolambda/blob/605a10acf6aec9449ce5792068dd733dc62ab336/README.md

### CODE REVIEW

**Comment by konifar** [comment]
👀

**Comment by konifar** [comment]
Wow, this includes Jake's PR right?
I'll check a methods count 😃

**Comment by shaunkawano** [comment]
> Wow, this includes Jake's PR right?

That's right! Hopefully we can reduce decent amount of it. 😄

**Comment by konifar** [comment]
LGTM!

**Pull request merged**
