### PR TITLE
Update Dagger version to 2.4.

### PR DESCRIPTION
**Pull request by hotchemi**

### CODE REVIEW

**Comment by hotchemi** [comment]
ah

**Comment by shaunkawano** [comment]
@hotchemi 
This is weird 😮 I'm guessing it should pass. Why don't you try rebuilding it?

**Comment by hotchemi** [comment]
I re-executed ci build but it is still failing...

**Comment by shaunkawano** [comment]
it seems this issue may be a complicated one.. 😮 

- https://github.com/google/dagger/issues/356#issuecomment-215173598
- https://github.com/google/dagger/issues/356#issuecomment-215694014

**Comment by hotchemi** [comment]
OK, I close this pr because it's not urgent stuff actually.

**Comment by konifar** [comment]
Thanks. We'll try later 👍

**Comment by shaunkawano** [comment]
I agree with you, @hotchemi @konifar; seems like Google hasn't solved this original issue just yet.  https://github.com/google/dagger/issues/356#issuecomment-215694014

**Pull request closed without merging**
